language: java
sudo: false
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: DZTi2+W0rpdAQhTvBErLBzATCU1JTBSKtwHGOTe3h5cDeycF2rCk/4oSp8sQXAhTPh5374xJa7SQ4YiIxulLTFg5Fo+Y6Fd3J/2I0klI2mjHpWMyo7iBvwJUonu6uI00kzHtpRBoTnTx98sb6Vzcx4OzguZiFwuk0UrFfdqoDFLh7tFxwUL+T7m3ziKVAH6LXM3kzJJWn0+p/hZ+x/T/gUEW0bmeOMtme8Q+UuDNC/u4NzKdtCGFlhmLj3RoiiN6J0vEO1c2F3LcXTQ3akft955S5cab52o1HJussqh9pc4N4YE6PzGCX/pZ5vQmiXCah4jDXEixnt+2Ey/LvtUOdIdzwWgEd9fHKMHRZ35TEnwgv2qllYvqdqblmQ2IOKbEHnkXRkoBLFhM11f+Gu/F8qgMSOmWkbkMuCFD7xbWwlzzqrlKmDIGGDLa5Ch1fyLDnpze5wvoIUMARpqvPQW46mcMc8P6t5mFm5iHMQwHRHK7FUPoY9wLYLmsV6PlY6zc5Y6njnvKfxTSlD4cFf7ZpiNKCZpVazY3ptQIrjnA9JtYQjaiX2LAKBzzduj7mvb4nQS3N9k00qC/g9qjxIW0YbPwZdfX4QZv5q703aec7BumEiYCGvQciPU0fYsWplibE6rM1P5Lrihb/QjwvQDPitj2ZlUG/zwColKpT4MtBLo=
  file: "/home/travis/.m2/repository/ch/bbw/ConsoleCalculator02/0.0.1-SNAPSHOT/ConsoleCalculator02-0.0.1-SNAPSHOT.jar"
  on:
    repo: 5ia17masancassani/ConsoleCalculator02
